### ISSUE TITLE
vars.env?

### ISSUE THREAD

**Issue by altsanz** [kyunwang/note-detector#1]
Hi! Great work! I would like to run it locally but it returns 
```
> note-detector@1.0.0 dev C:\Users\sanzdiaa\projects\note-detector
> webpack-serve --config=./webpack.config.js

Error: An error was thrown while initializing koa-webpack 
 TypeError: Cannot read property 'server' of undefined
    at module.exports (C:\Users\sanzdiaa\projects\note-detector\node_modules\webpack-hot-client\lib\options.js:52:28)
    at C:\Users\sanzdiaa\projects\note-detector\node_modules\koa-webpack\lib\index.js:19:20
    at new Promise (<anonymous>)
    at getClient (C:\Users\sanzdiaa\projects\note-detector\node_modules\koa-webpack\lib\index.js:18:10)
    at module.exports (C:\Users\sanzdiaa\projects\note-detector\node_modules\koa-webpack\lib\index.js:87:10)
    at WebpackMiddleware.call (C:\Users\sanzdiaa\projects\note-detector\node_modules\webpack-serve\lib\middleware\WebpackMiddleware.js:29:12)
    at C:\Users\sanzdiaa\projects\note-detector\node_modules\webpack-serve\lib\middleware\MiddlewareState.js:11:17
    at C:\Users\sanzdiaa\projects\note-detector\node_modules\webpack-serve\node_modules\mem\index.js:36:18
    at C:\Users\sanzdiaa\projects\note-detector\node_modules\webpack-serve\lib\app.js:50:34
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at C:\Users\sanzdiaa\projects\note-detector\node_modules\webpack-serve\lib\middleware\WebpackMiddleware.js:49:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

May it be because I dont have vars.env file? What would  be the content? Thank you!

**Comment by kyunwang** [comment]
Hi, nice catch! Did forgot to put that step in it indeed.

The vars.env is quite basic. You will need to put in the host and port only. Nothing too sensitive there.

```
HOST=localhost
PORT=8000
```

Also, did a quick update to the repo. It was in a partial broken state due to the autoplay policy 🤷‍♂️. It used to start immediately on page load. Now the controls are available. Like you can see here https://kyunwang.github.io/note-detector/

Don't have the time at the moment to do a documentation update but put it in the index.js in this repo.

Anyway, enjoy your weekend.

**Comment by altsanz** [comment]
Hi Kevin!

So nice! Thank you very much! I was like building a prod and serving it with http-server, which was A MUCH SLOWER process haha. I realize also the autoplay policy. Fixed that already. I’ve been creating like a realtime tone tracker with chartJS. 

Have a nice weekend you too!

**Comment by kyunwang** [comment]
Sounds cool! If you ever feel like sharing what you've made, please do!

Closing this issue now.
